/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package test;


import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import utility.DataOb;

/**
 *
 * @author SACHITHA
 */
public class AddMedicine extends javax.swing.JFrame {

    /**
     * Creates new form AddMedicine
     */
    public AddMedicine() {
        initComponents();
        
        this.setTitle("Add Medicine");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        textQty = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        textExpDate = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        textDesc = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        textID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textUnitPrice = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setBackground(new java.awt.Color(42, 79, 153));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/Sources/left.png"))); // NOI18N
        btnBack.setBorderPainted(false);
        btnBack.setContentAreaFilled(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 40, 40));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Quantity");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 104, 120, 30));

        textQty.setBackground(new java.awt.Color(255, 255, 255));
        textQty.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        textQty.setForeground(new java.awt.Color(0, 0, 0));
        textQty.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(textQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 140, 170, 28));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Exp Date");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 186, 120, 30));

        textExpDate.setBackground(new java.awt.Color(255, 255, 255));
        textExpDate.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        textExpDate.setForeground(new java.awt.Color(204, 204, 204));
        textExpDate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textExpDate.setText("YYYY/MM/dd");
        textExpDate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textExpDateMouseClicked(evt);
            }
        });
        textExpDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textExpDateActionPerformed(evt);
            }
        });
        textExpDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textExpDateKeyPressed(evt);
            }
        });
        jPanel1.add(textExpDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 222, 170, 28));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Med Description");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 268, 120, 30));

        textDesc.setBackground(new java.awt.Color(255, 255, 255));
        textDesc.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        textDesc.setForeground(new java.awt.Color(0, 0, 0));
        textDesc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(textDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 304, 170, 28));

        jButton1.setBackground(new java.awt.Color(0, 204, 204));
        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/Sources/save.png"))); // NOI18N
        jButton1.setText("Save");
        jButton1.setBorderPainted(false);
        jButton1.setOpaque(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 370, 100, 35));

        btnClear.setBackground(new java.awt.Color(0, 204, 204));
        btnClear.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnClear.setForeground(new java.awt.Color(0, 0, 0));
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/Sources/broom.png"))); // NOI18N
        btnClear.setText("Clear");
        btnClear.setBorderPainted(false);
        btnClear.setOpaque(true);
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel1.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 370, 100, 35));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Product ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 104, 120, 30));

        textID.setBackground(new java.awt.Color(255, 255, 255));
        textID.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        textID.setForeground(new java.awt.Color(0, 0, 0));
        textID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(textID, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 140, 170, 28));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Product Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 186, 120, 30));

        textName.setBackground(new java.awt.Color(255, 255, 255));
        textName.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        textName.setForeground(new java.awt.Color(0, 0, 0));
        textName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(textName, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 222, 170, 28));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Unit Price");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 262, 120, 30));

        textUnitPrice.setBackground(new java.awt.Color(255, 255, 255));
        textUnitPrice.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        textUnitPrice.setForeground(new java.awt.Color(0, 0, 0));
        textUnitPrice.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(textUnitPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 298, 170, 28));

        jLabel8.setBackground(new java.awt.Color(42, 79, 153));
        jLabel8.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("New Medicine");
        jLabel8.setOpaque(true);
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 25, 557, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        textID.setText("");
        textName.setText("");
        textUnitPrice.setText("");
        textQty.setText("");
        textExpDate.setText("");
        textDesc.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            DataOb.dbConnects();
            String sql = "insert into medicine values ( '"+textID.getText()+ "', '"+textName.getText() + "', '"+textUnitPrice.getText() + "')";
            //                   "', '"+ textQty.getText() + "', '"+ textExpDate.getText()+ "', '"+textMadeDate.getText()+"' )";
            DataOb.insertManual(sql);

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddMedicine.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(AddMedicine.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(AddMedicine.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AddMedicine.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(AddMedicine.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void textExpDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textExpDateActionPerformed
        
    }//GEN-LAST:event_textExpDateActionPerformed

    private void textExpDateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textExpDateMouseClicked
        textExpDate.setText("");
        textExpDate.setForeground(Color.BLACK);
    }//GEN-LAST:event_textExpDateMouseClicked

    private void textExpDateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textExpDateKeyPressed
       // textExpDate.setText("");
    }//GEN-LAST:event_textExpDateKeyPressed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        
        products pro = new products();
        pro.setVisible(false);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddMedicine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField textDesc;
    private javax.swing.JTextField textExpDate;
    private javax.swing.JTextField textID;
    private javax.swing.JTextField textName;
    private javax.swing.JTextField textQty;
    private javax.swing.JTextField textUnitPrice;
    // End of variables declaration//GEN-END:variables
}
