
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import java.awt.Color;
import static java.awt.Color.WHITE;
import java.awt.Cursor;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author SACHITHA
 */
public class Register extends javax.swing.JFrame implements Runnable{

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
        Thread t = new Thread(this);
        t.start();
        
        int r = 0;
        int g = 0;
        int b = 0;
        int a = 35;
        
        lblName.setBackground(new java.awt.Color(r,g,b,a));
        lblAddress.setBackground(new java.awt.Color(r,g,b,a));
        lblCity.setBackground(new java.awt.Color(r,g,b,a));
        lblCont.setBackground(new java.awt.Color(r,g,b,a));
        lblBirth.setBackground(new java.awt.Color(r,g,b,a));
        lblAge.setBackground(new java.awt.Color(r,g,b,a));
        lblEmail.setBackground(new java.awt.Color(r,g,b,a));
        lblNIC.setBackground(new java.awt.Color(r,g,b,a));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        lblAddress = new javax.swing.JLabel();
        txtCityy = new javax.swing.JTextField();
        lblCity = new javax.swing.JLabel();
        txtContact = new javax.swing.JTextField();
        lblCont = new javax.swing.JLabel();
        txtDob = new javax.swing.JTextField();
        lblBirth = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        lblAge = new javax.swing.JLabel();
        txtNIC = new javax.swing.JTextField();
        lblNIC = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();
        lblTime = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sources/icons8-minimize-window-48.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 20, 20));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sources/close.jpg"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 20, 20));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REGISTER FORM");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(0, 51, 102), new java.awt.Color(0, 51, 102), new java.awt.Color(0, 51, 102), new java.awt.Color(0, 51, 102)));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 24, 400, 60));

        lblName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText(" FULL NAME");
        lblName.setOpaque(true);
        jPanel1.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 108, 140, 35));

        txtName.setBackground(new java.awt.Color(0, 0, 102));
        txtName.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        txtName.setForeground(new java.awt.Color(83, 88, 89));
        txtName.setText("--Name--");
        txtName.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtName.setOpaque(true);
        txtName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNameMouseClicked(evt);
            }
        });
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNameKeyReleased(evt);
            }
        });
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 108, 370, 35));

        txtAddress.setBackground(new java.awt.Color(0, 0, 102));
        txtAddress.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        txtAddress.setForeground(new java.awt.Color(83, 88, 89));
        txtAddress.setText("--Address--");
        txtAddress.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtAddress.setOpaque(true);
        txtAddress.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAddressMouseClicked(evt);
            }
        });
        txtAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAddressKeyReleased(evt);
            }
        });
        jPanel1.add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 161, 370, 35));

        lblAddress.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAddress.setForeground(new java.awt.Color(255, 255, 255));
        lblAddress.setText(" ADDRESS");
        lblAddress.setOpaque(true);
        jPanel1.add(lblAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 161, 140, 35));

        txtCityy.setBackground(new java.awt.Color(0, 0, 102));
        txtCityy.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        txtCityy.setForeground(new java.awt.Color(83, 88, 89));
        txtCityy.setText("--City--");
        txtCityy.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtCityy.setOpaque(true);
        txtCityy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCityyMouseClicked(evt);
            }
        });
        txtCityy.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCityyKeyReleased(evt);
            }
        });
        jPanel1.add(txtCityy, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 214, 370, 35));

        lblCity.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCity.setForeground(new java.awt.Color(255, 255, 255));
        lblCity.setText(" CITY");
        lblCity.setOpaque(true);
        jPanel1.add(lblCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 214, 140, 35));

        txtContact.setBackground(new java.awt.Color(0, 0, 102));
        txtContact.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        txtContact.setForeground(new java.awt.Color(83, 88, 89));
        txtContact.setText("--Contact No--");
        txtContact.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtContact.setOpaque(true);
        txtContact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtContactMouseClicked(evt);
            }
        });
        txtContact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtContactKeyReleased(evt);
            }
        });
        jPanel1.add(txtContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 267, 370, 35));

        lblCont.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCont.setForeground(new java.awt.Color(255, 255, 255));
        lblCont.setText(" CONTACT NO.");
        lblCont.setOpaque(true);
        jPanel1.add(lblCont, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 267, 140, 35));

        txtDob.setBackground(new java.awt.Color(0, 0, 102));
        txtDob.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        txtDob.setForeground(new java.awt.Color(83, 88, 89));
        txtDob.setText("--YYYY/MM/DD--");
        txtDob.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtDob.setOpaque(true);
        txtDob.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDobMouseClicked(evt);
            }
        });
        txtDob.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDobKeyReleased(evt);
            }
        });
        jPanel1.add(txtDob, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 320, 370, 35));

        lblBirth.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblBirth.setForeground(new java.awt.Color(255, 255, 255));
        lblBirth.setText(" BIRTHDAY");
        lblBirth.setOpaque(true);
        jPanel1.add(lblBirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 320, 140, 35));

        txtAge.setBackground(new java.awt.Color(0, 0, 102));
        txtAge.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        txtAge.setForeground(new java.awt.Color(83, 88, 89));
        txtAge.setText("--Age--");
        txtAge.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtAge.setOpaque(true);
        txtAge.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAgeMouseClicked(evt);
            }
        });
        txtAge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAgeKeyReleased(evt);
            }
        });
        jPanel1.add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 373, 370, 35));

        lblAge.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAge.setForeground(new java.awt.Color(255, 255, 255));
        lblAge.setText(" AGE");
        lblAge.setOpaque(true);
        jPanel1.add(lblAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 373, 140, 35));

        txtNIC.setBackground(new java.awt.Color(0, 0, 102));
        txtNIC.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        txtNIC.setForeground(new java.awt.Color(83, 88, 89));
        txtNIC.setText("--NIC--");
        txtNIC.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtNIC.setOpaque(true);
        txtNIC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNICMouseClicked(evt);
            }
        });
        txtNIC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNICKeyReleased(evt);
            }
        });
        jPanel1.add(txtNIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 426, 370, 35));

        lblNIC.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNIC.setForeground(new java.awt.Color(255, 255, 255));
        lblNIC.setText(" NIC");
        lblNIC.setOpaque(true);
        jPanel1.add(lblNIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 426, 140, 35));

        txtEmail.setBackground(new java.awt.Color(0, 0, 102));
        txtEmail.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(83, 88, 89));
        txtEmail.setText("--Email--");
        txtEmail.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtEmail.setOpaque(true);
        txtEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtEmailMouseClicked(evt);
            }
        });
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmailKeyReleased(evt);
            }
        });
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 479, 370, 35));

        lblEmail.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail.setText(" E - MAIL");
        lblEmail.setOpaque(true);
        jPanel1.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 479, 140, 38));

        btnRegister.setBackground(new java.awt.Color(0, 204, 204));
        btnRegister.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(0, 0, 0));
        btnRegister.setText("Register");
        btnRegister.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRegister.setBorderPainted(false);
        btnRegister.setOpaque(true);
        btnRegister.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnRegisterMouseMoved(evt);
            }
        });
        btnRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegisterMouseExited(evt);
            }
        });
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 530, 200, 60));

        lblTime.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblTime.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, 90, 30));

        lblDate.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblDate.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 80, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sources/Untitled-4.jpg"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 600));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyReleased
        char letter = evt.getKeyChar();
        if(Character.isLetter(letter)| evt.getKeyCode() == KeyEvent.VK_SPACE | evt.getKeyCode() == KeyEvent.VK_BACK_SPACE 
                | evt.getKeyCode() == KeyEvent.VK_CAPS_LOCK |evt.getKeyCode() == KeyEvent.VK_ENTER | evt.getKeyCode() == KeyEvent.VK_SHIFT 
                | evt.getKeyCode() == KeyEvent.VK_PERIOD | evt.getKeyCode() == KeyEvent.VK_LEFT | evt.getKeyCode() == KeyEvent.VK_RIGHT){
            
            txtName.setEditable(true);
            
        }else{
            txtName.setEditable(false);
            JOptionPane.showMessageDialog(this, "plz enter alpherbit character","ERROR",JOptionPane.ERROR_MESSAGE);
            
                txtName.grabFocus();
                txtName.setText("");
            
                
                   
        }
    }//GEN-LAST:event_txtNameKeyReleased

    private void txtAddressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAddressKeyReleased
        char charactor = evt.getKeyChar();
        if(Character.isDigit(charactor)|Character.isLetter(charactor)|evt.getKeyCode() == KeyEvent.VK_BACK_SPACE | evt.getKeyCode() == KeyEvent.VK_SPACE
                | evt.getKeyCode() == KeyEvent.VK_ENTER | evt.getKeyCode() == KeyEvent.VK_SHIFT | evt.getKeyCode() == KeyEvent.VK_2|evt.getKeyCode() == KeyEvent.VK_MINUS
                | evt.getKeyCode() == KeyEvent.VK_PERIOD | evt.getKeyCode() == KeyEvent.VK_LEFT | evt.getKeyCode() == KeyEvent.VK_RIGHT | evt.getKeyCode() == KeyEvent.VK_COMMA
                | evt.getKeyCode() == KeyEvent.VK_SLASH){
            
            txtAddress.setEditable(true);
        }else{
            txtAddress.setEditable(false);
            JOptionPane.showMessageDialog(this, "plz enter Valid character","ERROR",JOptionPane.ERROR_MESSAGE);
            if(evt.getKeyCode() == KeyEvent.VK_ENTER)
                txtAddress.grabFocus();
            txtAddress.setText("");
            txtAddress.grabFocus();
                    
        }
    }//GEN-LAST:event_txtAddressKeyReleased

    private void txtCityyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCityyKeyReleased
        char letter = evt.getKeyChar();
        if(Character.isLetter(letter)| evt.getKeyCode() == KeyEvent.VK_SPACE | evt.getKeyCode() == KeyEvent.VK_BACK_SPACE 
                | evt.getKeyCode() == KeyEvent.VK_CAPS_LOCK | evt.getKeyCode() == KeyEvent.VK_ENTER | evt.getKeyCode() == KeyEvent.VK_SHIFT 
                | evt.getKeyCode() == KeyEvent.VK_LEFT | evt.getKeyCode() == KeyEvent.VK_RIGHT){
            
            txtCityy.setEditable(true);
        }else{
            txtCityy.setEditable(false);
            JOptionPane.showMessageDialog(this, "plz enter alpherbit character","ERROR",JOptionPane.ERROR_MESSAGE);
            if(evt.getKeyCode() == KeyEvent.VK_ENTER)
                txtCityy.grabFocus();
            txtCityy.setText("");
            txtCityy.grabFocus();
                    
        }
    }//GEN-LAST:event_txtCityyKeyReleased

    private void txtContactKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContactKeyReleased
        char number = evt.getKeyChar();
        if(Character.isDigit(number)|  evt.getKeyCode() == KeyEvent.VK_BACK_SPACE |  evt.getKeyCode() == KeyEvent.VK_SHIFT
                |  evt.getKeyCode() == KeyEvent.VK_EQUALS |  evt.getKeyCode() == KeyEvent.VK_MINUS
                | evt.getKeyCode() == KeyEvent.VK_ENTER  |  evt.getKeyCode() == KeyEvent.VK_LEFT | evt.getKeyCode() == KeyEvent.VK_RIGHT){
            
            txtContact.setEditable(true);
        }else{
            txtContact.setEditable(false);
            JOptionPane.showMessageDialog(this, "plz enter Numeric character","ERROR",JOptionPane.ERROR_MESSAGE);
            if(evt.getKeyCode() == KeyEvent.VK_ENTER)
                txtContact.grabFocus();
            txtContact.setText("");
            txtContact.grabFocus();
                    
        }
    }//GEN-LAST:event_txtContactKeyReleased

    private void txtDobKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDobKeyReleased
        char number = evt.getKeyChar();
        if(Character.isDigit(number)|  evt.getKeyCode() == KeyEvent.VK_BACK_SPACE |  evt.getKeyCode() == KeyEvent.VK_SHIFT
                |  evt.getKeyCode() == KeyEvent.VK_MINUS| evt.getKeyCode() == KeyEvent.VK_SLASH| evt.getKeyCode() == KeyEvent.VK_PERIOD
                | evt.getKeyCode() == KeyEvent.VK_ENTER  |  evt.getKeyCode() == KeyEvent.VK_LEFT | evt.getKeyCode() == KeyEvent.VK_RIGHT){
            
            txtDob.setEditable(true);
        }else{
            txtDob.setEditable(false);
            JOptionPane.showMessageDialog(this, "plz enter Numeric character","ERROR",JOptionPane.ERROR_MESSAGE);
            if(evt.getKeyCode() == KeyEvent.VK_ENTER)
                txtDob.grabFocus();
            txtDob.setText("");
            txtDob.grabFocus();
                    
        }
    }//GEN-LAST:event_txtDobKeyReleased

    private void txtAgeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAgeKeyReleased
        char number = evt.getKeyChar();
        if(Character.isDigit(number)|  evt.getKeyCode() == KeyEvent.VK_BACK_SPACE | evt.getKeyCode() == KeyEvent.VK_ENTER  
                |  evt.getKeyCode() == KeyEvent.VK_LEFT | evt.getKeyCode() == KeyEvent.VK_RIGHT){
            
            txtAge.setEditable(true);
        }else{
            txtAge.setEditable(false);
            JOptionPane.showMessageDialog(this, "plz enter Numeric character","ERROR",JOptionPane.ERROR_MESSAGE);
            if(evt.getKeyCode() == KeyEvent.VK_ENTER)
                txtAge.grabFocus();
            txtAge.setText("");
            txtAge.grabFocus();
                    
        }
    }//GEN-LAST:event_txtAgeKeyReleased

    private void txtNICKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNICKeyReleased
        char charactor = evt.getKeyChar();
        if(Character.isDigit(charactor)| evt.getKeyCode() == KeyEvent.VK_V | evt.getKeyCode() == KeyEvent.VK_ENTER | 
                evt.getKeyCode() == KeyEvent.VK_LEFT | evt.getKeyCode() == KeyEvent.VK_RIGHT |evt.getKeyCode() == KeyEvent.VK_BACK_SPACE ){
            txtNIC.setEditable(true);
        }else{
            txtNIC.setEditable(false);
            JOptionPane.showMessageDialog(this, "plz enter Valid character","ERROR",JOptionPane.ERROR_MESSAGE);
            if(evt.getKeyCode() == KeyEvent.VK_ENTER | evt.getKeyCode() == KeyEvent.VK_SHIFT)
                txtNIC.grabFocus();
            txtNIC.setText("");
            txtNIC.grabFocus();
        }
    }//GEN-LAST:event_txtNICKeyReleased

    private void txtEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyReleased
        char charactor = evt.getKeyChar();
        if(Character.isDigit(charactor)|Character.isLetter(charactor)|evt.getKeyCode() == KeyEvent.VK_BACK_SPACE 
                | evt.getKeyCode() == KeyEvent.VK_ENTER | evt.getKeyCode() == KeyEvent.VK_SHIFT | evt.getKeyCode() == KeyEvent.VK_2
                | evt.getKeyCode() == KeyEvent.VK_PERIOD | evt.getKeyCode() == KeyEvent.VK_LEFT | evt.getKeyCode() == KeyEvent.VK_RIGHT){
            
            txtEmail.setEditable(true);
        }else{
            txtEmail.setEditable(false);
            JOptionPane.showMessageDialog(this, "plz enter Valid character","ERROR",JOptionPane.ERROR_MESSAGE);
            if(evt.getKeyCode() == KeyEvent.VK_ENTER)
                txtEmail.grabFocus();
            txtEmail.setText("");
            txtEmail.grabFocus();
                    
        }
    }//GEN-LAST:event_txtEmailKeyReleased

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        if(txtName.getText().isEmpty() || txtAddress.getText().isEmpty() || txtCityy.getText().isEmpty() || txtContact.getText().isEmpty() ||txtDob.getText().isEmpty() ||
                txtAge.getText().isEmpty() || txtNIC.getText().isEmpty() || txtEmail.getText().isEmpty() ){
            JOptionPane.showMessageDialog(this, "Fill The All Details!", "Warnnig", JOptionPane.WARNING_MESSAGE);
        }else{
            if(contact() == 1 && birthday() ==1 && age() == 1 && nic() == 1 && email() == 1){
                JOptionPane.showMessageDialog(this, "Registration Succsessfull!", "Correct", JOptionPane.DEFAULT_OPTION);
            }
            
        }
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnRegisterMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegisterMouseMoved
        btnRegister.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        btnRegister.setBackground(Color.BLUE);
        btnRegister.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnRegisterMouseMoved

    private void btnRegisterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegisterMouseExited
        btnRegister.setBackground(new java.awt.Color(0, 204, 204));
        btnRegister.setForeground(Color.BLACK);
        btnRegister.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    }//GEN-LAST:event_btnRegisterMouseExited

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNameMouseClicked
        txtName.setText("");
        txtName.setForeground(WHITE);
    }//GEN-LAST:event_txtNameMouseClicked

    private void txtAddressMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAddressMouseClicked
        txtAddress.setText("");
        txtAddress.setForeground(WHITE);
    }//GEN-LAST:event_txtAddressMouseClicked

    private void txtCityyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCityyMouseClicked
        txtCityy.setText("");
        txtCityy.setForeground(WHITE);
    }//GEN-LAST:event_txtCityyMouseClicked

    private void txtContactMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtContactMouseClicked
        txtContact.setText("");
        txtContact.setForeground(WHITE);
    }//GEN-LAST:event_txtContactMouseClicked

    private void txtDobMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDobMouseClicked
        txtDob.setText("");
        txtDob.setForeground(WHITE);
    }//GEN-LAST:event_txtDobMouseClicked

    private void txtAgeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAgeMouseClicked
        txtAge.setText("");
        txtAge.setForeground(WHITE);
    }//GEN-LAST:event_txtAgeMouseClicked

    private void txtNICMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNICMouseClicked
        txtNIC.setText("");
        txtNIC.setForeground(WHITE);
    }//GEN-LAST:event_txtNICMouseClicked

    private void txtEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEmailMouseClicked
        txtEmail.setText("");
        txtEmail.setForeground(WHITE);
    }//GEN-LAST:event_txtEmailMouseClicked

    public int contact(){
        String x = txtContact.getText();
        int y = x.length();
        if(y > 8 && y < 12 | y == 12 | y == 13 | y==14){
            if (y == 12 | y == 13 | y==14){
                if(txtContact.getText().contains("+"))
                    return 1;
                else
                    JOptionPane.showMessageDialog(this, "Should be '+' ","Contact No Error",JOptionPane.ERROR_MESSAGE);
            }  
            return 1;
        }else
                JOptionPane.showMessageDialog(this, "Contact Number Is Wrong, Plz Try Again!","Contact Number Error",JOptionPane.ERROR_MESSAGE);
        return 0;
    }
    
    public int birthday(){
        String x = txtDob.getText();
        if(x.contains("/") || x.contains("-")){
            return 1;
        }else
            JOptionPane.showMessageDialog(this, "Plz Fill 'YYYY/MM/DD' This Foramat","Birthday Warning",JOptionPane.WARNING_MESSAGE);
        return 0;
                                     
    }
    public int age(){
        String x = txtAge.getText();
        int y = Integer.parseInt(x);
        if(y > 0 && y < 100){
            return 1;
        }else
            JOptionPane.showMessageDialog(this, "Plz Enter Correct Age!","Age Warning",JOptionPane.WARNING_MESSAGE);
        return 0;
            
    }
    public int nic(){
        String x = txtNIC.getText();
        int y = x.length();
        if(x.trim().matches("^[0-9]{9}[vV]$") || x.trim().matches("^[0-9]{12}")){
            return 1;
        }else
            JOptionPane.showMessageDialog(this, "Plz Enter Valid NIC Number!","NIC Error",JOptionPane.ERROR_MESSAGE);
        return 0;
        
    }
    public int email(){
        String x = txtEmail.getText();
        if(x.contains("@") && x.contains(".")){
            return 1;
        }else
            JOptionPane.showMessageDialog(this, "Plz Enter Valid E-mail!","E-Mail Error",JOptionPane.ERROR_MESSAGE);
        return 0;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblBirth;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCont;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblNIC;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblTime;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtCityy;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtDob;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNIC;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        while(true){
            Calendar c = Calendar.getInstance();
            int hour = c.get(Calendar.HOUR_OF_DAY);
            if(hour > 12)
                hour = hour - 12;
            int minute = c.get(Calendar.MINUTE);
            int second = c.get(Calendar.SECOND);
            int day = c.get(Calendar.DAY_OF_MONTH);
            int month = c.get(Calendar.MONTH);
            int year = c.get(Calendar.YEAR);

            SimpleDateFormat date = new SimpleDateFormat("YYYY/MM/DD");
            SimpleDateFormat time = new SimpleDateFormat("hh:mm:ss a");

            Date d = c.getTime();

            String displayDate = date.format(d);
            String displayTIme = time.format(d);

            lblDate.setText(displayDate);
            lblTime.setText(displayTIme);
        }
    }

    
}
